GrupoOnzeFaculdade/Models/CadastroAluno.cs
using System.ComponentModel.DataAnnotations;

namespace GrupoOnzeFaculdade.Models
{
    public class CadastroAluno
    {
        public int id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Nome")]
        public required string nome { get; set; }
        [Display(Name = "Sobrenome")]
        public string? sobrenome { get; set; }
        [Display(Name = "Matrícula")]
        public string? matricula { get; set; }
        [Display(Name = "Endereço")]
        public string? endereco { get; set; }

        [Display(Name = "Telefone")]
        public string? telefone { get; set; }

    }
}

GrupoOnzeFaculdade/Models/ErrorViewModel.cs
namespace GrupoOnzeFaculdade.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GrupoOnzeFaculdade/Controllers/CadastroAlunoController.cs
using GrupoOnzeFaculdade.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Xml;

public class CadastroAlunoController : Controller
{
    private readonly ApplicationDbContext _context;

    public CadastroAlunoController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: CadastroAlunos
    public async Task<IActionResult> Index()
    {
        return View(await _context.cadastro_aluno.ToListAsync());
    }

    // GET: CadastroAlunos/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cadastroAluno = await _context.cadastro_aluno
            .FirstOrDefaultAsync(c => c.id == id);
        if (cadastroAluno == null)
        {
            return NotFound();
        }

        return View(cadastroAluno);
    }

    // GET: CadastroAlunos/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: CadastroAlunos/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("id,nome,sobrenome,matricula,endereco,telefone")] CadastroAluno cadastroAluno)
    {
        if (ModelState.IsValid)
        {
            _context.Add(cadastroAluno);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(cadastroAluno);
    }

    // GET: CadastroAlunos/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cadastroAluno = await _context.cadastro_aluno.FindAsync(id);
        if (cadastroAluno == null)
        {
            return NotFound();
        }
        return View(cadastroAluno);
    }

    // POST: CadastroAlunos/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("id,nome,sobrenome,matricula,endereco,telefone")] CadastroAluno cadastroAluno)
    {
        if (id != cadastroAluno.id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(cadastroAluno);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!cadastroAlunoExists(cadastroAluno.id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(cadastroAluno);
    }

    // GET: CadastroAlunos/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cadastroAluno = await _context.cadastro_aluno
            .FirstOrDefaultAsync(c => c.id == id);
        if (cadastroAluno == null)
        {
            return NotFound();
        }

        return View(cadastroAluno);
    }



    // POST: CadastroAlunos/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var cadastroAluno = await _context.cadastro_aluno.FindAsync(id);
        _context.cadastro_aluno.Remove(cadastroAluno);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool cadastroAlunoExists(int id)
    {
        return _context.cadastro_aluno.Any(e => e.id == id);
    }
}

GrupoOnzeFaculdade/Controllers/HomeController.cs
using GrupoOnzeFaculdade.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GrupoOnzeFaculdade.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult PoliticaSeguranca()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GrupoOnzeFaculdade/Controllers/PdfController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.IO;

public class PdfController : Controller
{
    private readonly IWebHostEnvironment _webHostEnvironment;

    public PdfController(IWebHostEnvironment webHostEnvironment)
    {
        _webHostEnvironment = webHostEnvironment;
    }

    // Ação para servir o PDF
    public IActionResult ViewPdf(string fileName)
    {
        string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "pdf", fileName);
        if (!System.IO.File.Exists(filePath))
        {
            return NotFound();
        }
        byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
        return File(fileBytes, "application/pdf");
    }

    // Ação para exibir a view que contém o iframe
    public IActionResult Pdf()
    {
        return View();
    }
}

GrupoOnzeFaculdade/Views/CadastroAluno/Create.cshtml
@model GrupoOnzeFaculdade.Models.CadastroAluno
@{
    ViewData["Title"] = "Create";
}

<h1 style="text-align:left">Casastro de Novo Aluno</h1>

<h4 style="text-align:left">Preencha os dados abaixo</h4>
<hr />
<div class="row" style="text-align:left">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sobrenome" class="control-label"></label>
                <input asp-for="sobrenome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="matricula" class="control-label"></label>
                <input asp-for="matricula" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="endereco" class="control-label"></label>
                <input asp-for="endereco" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
            </div>
           <p>

        </p>
        <p>

        </p>
        <p>

        </p>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<p>

        </p>
        <p>

        </p>
        <p>

        </p>

<div>
    <a asp-action="Index">Voltar para Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GrupoOnzeFaculdade/Views/CadastroAluno/Delete.cshtml
@model GrupoOnzeFaculdade.Models.CadastroAluno
@{
    ViewData["Title"] = "Delete";
}

<h1 style="text-align:left">Deletar Aluno</h1>

<h3 style="text-align:left">Tem certeza que deseja deletar esse cadastro?</h3>
<div style="text-align:left">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.sobrenome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.sobrenome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.matricula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.matricula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.endereco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.endereco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <p>

        </p>
        <p>

        </p>
        <p>

        </p>
        <a asp-action="Index">Voltar para Lista</a>
    </form>
</div>

GrupoOnzeFaculdade/Views/CadastroAluno/Edit.cshtml
@model GrupoOnzeFaculdade.Models.CadastroAluno

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar dados do aluno</h1>

<hr />
<div class="row" style="text-align:left">
    
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sobrenome" class="control-label"></label>
                <input asp-for="sobrenome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="matricula" class="control-label"></label>
                <input asp-for="matricula" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="endereco" class="control-label"></label>
                <input asp-for="endereco" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
            </div>
            <p>

        </p>
        <p>

        </p>
        <p>

        </p>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<p>

        </p>
        <p>

        </p>
        <p>

        </p>
<div>
    <a asp-action="Index">Voltar Para Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GrupoOnzeFaculdade/Views/CadastroAluno/Index.cshtml
@model IEnumerable<CadastroAluno>

@{
    ViewData["Title"] = "Index";
}
<p>

</p><p>

</p><p>

</p><p>

</p><p>

</p><p>

</p>
<h1 style="text-align:left" >CRUD - Lista de Alunos</h1>
<p>

</p><p>

</p><p>

</p><p>

</p><p>

</p><p>

</p>
<p style="text-align:left">
    
    <a asp-action="Create">Cadastrar Novo Aluno</a>
</p>
<p>

</p><p>

</p><p>

</p><p>

</p><p>

</p><p>

</p><p>

</p>
<table class="table" style="text-align:left">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sobrenome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sobrenome)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

GrupoOnzeFaculdade/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <style>
        /* Estilos CSS */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
            justify-content:left;
        }
        header {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 20px 0;
        }
        nav {
            background-color: #444;
            color: #fff;
            text-align: center;
            padding: 10px 0;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            padding: 0 10px;
        }
        section {
            padding: 20px;
        }
        .campus {
            margin-bottom: 20px;
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .campus h2 {
            color: #333;
        }
        .noticias {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        .noticia {
            width: 30%;
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
        .noticia h3 {
            color: #333;
        }
        .noticia p {
            color: #666;
        }
        .cursos {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        .curso {
            width: 30%;
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
        .curso h3 {
            color: #333;
        }
        .curso img {
            width: 100%; /* Todas as imagens ocuparão 100% da largura da div */
            height: auto; /* Manter a proporção da imagem */
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .curso p {
            color: #666;
        }
    </style>
    <section>

        <div class="campus" style="background-color:midnightblue; color:aliceblue">
            <h2 style ="background-color:midnightblue; color:aliceblue">
            Campus Matriz</h2>
            <p>Endereço: Rua da Faculdade, 123</p>
            <p>Telefone: (11) 1234-5678</p>
        </div>
        <h2>Notícias</h2>
        <div class="noticias">
            <div class="noticia">
                <h3>Novo Curso de Engenharia Civil</h3>
                <p>Estamos orgulhosos de anunciar o lançamento do novo curso de Engenharia Civil em nosso campus matriz. Saiba mais...</p>
            </div>
            <div class="noticia">
                <h3>Evento Cultural no Campus</h3>
                <p>No próximo sábado, teremos um evento cultural aberto ao público no nosso campus. Venha participar!</p>
            </div>
            <div class="noticia">
                <h3>Estudantes Premiados em Competição de Robótica</h3>
                <p>Nossos estudantes de Engenharia Mecatrônica conquistaram o primeiro lugar na competição regional de robótica. Parabéns!</p>
            </div>
        </div>
        <p>

        </p>
        <p>

        </p>
        <p>

        </p>
        <p>

        </p>
        <h2>Cursos Oferecidos</h2>
        <div class="cursos">
            <div class="curso">
                <h3>Engenharia Civil</h3>                
                <img src="~/img/engenharia-civil.jpg" alt="Engenharia Civil"/>
                <p>Conheça o curso de Engenharia Civil. Início das aulas em breve!</p>
            </div>
            <div class="curso">
                <h3>Eventos Culturais</h3>
                <img src="~/img/eventos_culturais.jpg" alt="Eventos Culturais">
                <p>Saiba mais sobre o curso de Organização de Eventos Culturais.</p>
            </div>
            <div class="curso">
                <h3>Engenharia Mecatrônica</h3>
                <img src="~/img/engenharia_mecatronica.jpg" alt="Engenharia Mecatrônica">
                <p>Descubra as oportunidades no curso de Engenharia Mecatrônica.</p>
            </div>
        </div>
    </section>
</>

GrupoOnzeFaculdade/Views/Home/PoliticaSeguranca.cshtml
@{
    ViewData["Title"] = "Política de Segurança";
}

<h1> </h1>

<div >

        <img src="~/img/seguranca-folder.jpeg" alt="Engenharia Civil" />

        
</div>

GrupoOnzeFaculdade/Views/Pdf/Pdf.cshtml
@{
    ViewBag.Title = "Documento do Curso";
}

<h2>Documento do Curso</h2>

<iframe src="@Url.Action("ViewPdf", "Pdf", new { fileName = "documento-curso.pdf" })" width="100%" height="800px">
    This browser does not support PDFs. Please download the PDF to view it: <a href="@Url.Action("ViewPdf", "Pdf", new { fileName = "documento-curso.pdf" })">Download PDF</a>.
</iframe>

GrupoOnzeFaculdade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GrupoOnzeFaculdade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GrupoOnzeFaculdade.styles.css" asp-append-version="true" />
</head>
<style>
    /* Estilos CSS */
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f2f2f2;
    }

    header {
        background-color: #333;
        color: #fff;
        text-align: center;
        padding: 20px 0;
    }

    nav {
        background-color: #444;
        color: #fff;
        text-align: center;
        padding: 10px 0;
    }

        nav a {
            color: #fff;
            text-decoration: none;
            padding: 0 10px;
        }

    section {
        padding: 20px;
    }

    .campus {
        margin-bottom: 20px;
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

        .campus h2 {
            color: #333;
        }

    .noticias {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .noticia {
        width: 30%;
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        .noticia h3 {
            color: #333;
        }

        .noticia p {
            color: #666;
        }

    .cursos {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .curso {
        width: 30%;
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        .curso h3 {
            color: #333;
        }

        .curso img {
            width: 100%; /* Todas as imagens ocuparão 100% da largura da div */
            height: auto; /* Manter a proporção da imagem */
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .curso p {
            color: #666;
        }
</style>
    
<body>
        <header style="background-color:midnightblue">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3" style="background-color:midnightblue">
                <div class="container-fluid" style="background-color:midnightblue">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:aliceblue">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="background-color:midnightblue; text-align:center">
                        <ul class="navbar-nav flex-grow-1" style="text-align:center">
                            <li class="nav-item" style="background-color:midnightblue">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" style="color:aliceblue !important; text-align:center">Home   |</a>
                            </li>
                            <li class="nav-item" style="background-color:midnightblue">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CadastroAluno" asp-action="Index" style="color:aliceblue !important; text-align:center">Cadastro de Aluno - CRUD   |</a>
                            </li>
                            <li class="nav-item" style="background-color:midnightblue">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PoliticaSeguranca" style="color:aliceblue !important; text-align:center">Cartilha de Segurança   |</a>
                            </li>

                            <li class="nav-item" style="background-color:midnightblue">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pdf" asp-action="Pdf" style="color:aliceblue !important; text-align:center">Documento - PROJETO INFRAESTRUTURA DE REDES</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GrupoOnzeFaculdade - <a asp-area="" asp-controller="Pdf" asp-action="Pdf" style="color:midnightblue !important; text-align:center">Documento - PROJETO INFRAESTRUTURA DE REDES</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>